### ISSUE TITLE
environment configuration

### ISSUE THREAD

**Issue by jesanli** [slothfulxtx/cxtrack3d#5]
Except for the special environment configuration of setup, is everything else the same as open3dsot requirement.txt?
Why does this project not exist the file enables novices to configure the environment.

**Comment by slothfulxtx** [comment]
Hi, most of our dependencies are the same as open3dsot. If you want further env details, you can find the dependencies list here
https://github.com/slothfulxtx/MBPTrack3D/blob/main/freeze.yml
