### ISSUE TITLE
Visualize the tracking results

### ISSUE THREAD

**Issue by ljg-101** [slothfulxtx/cxtrack3d#6]
Dear author，
I want to visualize the tracking results,but I don't know how to use the visualize.py file,In my understanding, running the visualize.py file requires a JSON file containing the tracking results. How can I modify the code to obtain this result file

**Comment by slothfulxtx** [comment]
Hi, you can run the test phase on your data to obtain the ``result.json''. Here is the relevant code

https://github.com/slothfulxtx/cxtrack3d/blob/a9eb6726905b03ccb4f6daceca82e147f5298e43/tasks/base_task.py#L260
